version: "3"

services:
  app:
    image: demo-app:dev
    deploy:
      replicas: 3
    networks:
      - demo-network

  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - demo-network
    depends_on:
      - app

networks:
  demo-network:
